import "./globals.css";
import Link from "next/link"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen p-20">
        <Link href="/" className="text-2xl font-bold">Home</Link>
        <main className="h-full pt-10">
          {children}
        </main>
      </body>
    </html>
  );
}
